---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: <%= ENV['CHEF_REPO'] || '~/workspace/cookbooks/chef12-repo/' %>/data_bags
  environments_path: <%= ENV['CHEF_REPO'] || '~/workspace/cookbooks/chef12-repo/' %>/environments
  client_rb:
    environment: development
  solo_rb:
    environment: development

driver_config:
  require_chef_omnibus: 12.13.37

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: jhcook/macos-sierra

suites:
  - name: sierra
    includes:
      - jhcook/macos-sierra
    driver:
      vm_hostname: sierra-osx.krs.io
      network:
      - ["private_network", {ip: "192.168.254.10"}]
    run_list:
      - recipe[osx-users::default]
      - recipe[osx-users::_erin_test]
    attributes:
      osx-users:
        attrs: 'blah'
