---
driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: 12.21.20

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: jhcook/macos-sierra

suites:
  - name: sierra
    includes:
      - jhcook/macos-sierra
    driver:
      vm_hostname: osx.elk.io
      network:
      - ["private_network", {ip: "192.168.254.10"}]
    run_list:
      - recipe[osx-users::default]
    attributes:
